import { Router } from 'express';
import { hello, health } from '../controllers/health.controller';
import authRoutes from './auth.routes';
import stylistRoutes from './stylist.routes';
import bookingRoutes from './booking.routes';
import reviewRoutes from './review.routes';
import queueRoutes from './queue.routes';
import paymentRoutes from './payment.routes';
import favoritesRoutes from './favorites.routes';
import notificationRoutes from './notification.routes';
import availabilityRoutes from './availability.routes';
import clientsRoutes from './clients.routes';
import conversationsRoutes from './conversations.routes';
import productsRoutes from './products.routes';
import packagesRoutes from './packages.routes';
import membershipsRoutes from './memberships.routes';
import marketingRoutes from './marketing.routes';
import waitlistRoutes from './waitlist.routes';
import consultationsRoutes from './consultations.routes';
import posRoutes from './pos.routes';
import settingsRoutes from './settings.routes';
import trendingRoutes from './trending.routes';
import engagementRoutes from './engagement.routes';
import commentRoutes from './comment.routes';
import areaRoutes from './area.routes';
import hairstyleRoutes from './hairstyle.routes';
import creditRoutes from './credit.routes';
import articleRoutes from './article.routes';
const router = Router();

router.get('/hello', hello);
router.get('/health', health);
router.use('/auth', authRoutes);
router.use('/stylists', stylistRoutes);
router.use('/trending', trendingRoutes);
router.use('/engagements', engagementRoutes);
router.use('/bookings', bookingRoutes);
router.use('/reviews', reviewRoutes);
router.use('/queue', queueRoutes);
router.use('/payments', paymentRoutes);
router.use('/favorites', favoritesRoutes);
router.use('/notifications', notificationRoutes);

router.use('/availability', availabilityRoutes);
router.use('/clients', clientsRoutes);
router.use('/conversations', conversationsRoutes);
router.use('/products', productsRoutes);
router.use('/packages', packagesRoutes);
router.use('/memberships', membershipsRoutes);
router.use('/marketing', marketingRoutes);
router.use('/waitlist', waitlistRoutes);
router.use('/consultations', consultationsRoutes);
router.use('/pos', posRoutes);
router.use('/settings', settingsRoutes);
router.use('/comments', commentRoutes);
router.use('/areas', areaRoutes);
router.use('/hairstyles', hairstyleRoutes);
router.use('/credits', creditRoutes);
router.use('/articles', articleRoutes);

export default router;
